name: Build

on: [push]

jobs:
  build_x86:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download Turbo Bob
      run: curl --fail --location --output bob https://dl.bintray.com/function61/dl/turbobob/20200617_1743_510a0529/bob_linux-amd64 && chmod +x bob
    - name: Build with Turbo Bob
      run: CI_REVISION_ID="$GITHUB_SHA" ./bob build --publish-artefacts
      env:
        DOCKER_CREDS: ${{ secrets.DOCKER_CREDS }}
  build_arm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ppawlowski/cc-tool  # list of Docker images to use as base name for tags
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
